interface SurahRuMeta {
  name: string
  translation: string
}

const data: SurahRuMeta[] = [
  { name: "Аль-Фатиха", translation: "Открывающая Коран" },
  { name: "Аль-Бакара", translation: "Корова" },
  { name: "Али Имран", translation: "Семейство Имрана" },
  { name: "Ан-Ниса", translation: "Женщины" },
  { name: "Аль-Маида", translation: "Трапеза" },
  { name: "Аль-Анам", translation: "Скот" },
  { name: "Аль-Араф", translation: "Ограды" },
  { name: "Аль-Анфаль", translation: "Трофеи" },
  { name: "Ат-Тауба", translation: "Покаяние" },
  { name: "Юнус", translation: "Юнус" },
  { name: "Худ", translation: "Худ" },
  { name: "Юсуф", translation: "Юсуф" },
  { name: "Ар-Раад", translation: "Гром" },
  { name: "Ибрахим", translation: "Ибрахим" },
  { name: "Аль-Хиджр", translation: "Хиджр" },
  { name: "Ан-Нахль", translation: "Пчёлы" },
  { name: "Аль-Исра", translation: "Ночной перенос" },
  { name: "Аль-Кахф", translation: "Пещера" },
  { name: "Марьям", translation: "Марьям" },
  { name: "Та Ха", translation: "Та Ха" },
  { name: "Аль-Анбия", translation: "Пророки" },
  { name: "Аль-Хадж", translation: "Паломничество" },
  { name: "Аль-Муминун", translation: "Верующие" },
  { name: "Ан-Нур", translation: "Свет" },
  { name: "Аль-Фуркан", translation: "Различение" },
  { name: "Аш-Шуара", translation: "Поэты" },
  { name: "Ан-Намль", translation: "Муравьи" },
  { name: "Аль-Касас", translation: "Рассказ" },
  { name: "Аль-Анкабут", translation: "Паук" },
  { name: "Ар-Рум", translation: "Римляне" },
  { name: "Лукман", translation: "Лукман" },
  { name: "Ас-Саджда", translation: "Земной поклон" },
  { name: "Аль-Ахзаб", translation: "Союзники" },
  { name: "Саба", translation: "Саба" },
  { name: "Фатыр", translation: "Творец" },
  { name: "Йа Син", translation: "Йа Син" },
  { name: "Ас-Саффат", translation: "Выстроившиеся в ряды" },
  { name: "Сад", translation: "Сад" },
  { name: "Аз-Зумар", translation: "Толпы" },
  { name: "Гафир", translation: "Прощающий" },
  { name: "Фуссилят", translation: "Разъяснены" },
  { name: "Аш-Шура", translation: "Совет" },
  { name: "Аз-Зухруф", translation: "Украшения" },
  { name: "Ад-Духан", translation: "Дым" },
  { name: "Аль-Джасия", translation: "Коленопреклонённые" },
  { name: "Аль-Ахкаф", translation: "Пески" },
  { name: "Мухаммад", translation: "Мухаммад" },
  { name: "Аль-Фатх", translation: "Победа" },
  { name: "Аль-Худжурат", translation: "Комнаты" },
  { name: "Каф", translation: "Каф" },
  { name: "Аз-Зарият", translation: "Рассеивающие прах" },
  { name: "Ат-Тур", translation: "Гора" },
  { name: "Ан-Наджм", translation: "Звезда" },
  { name: "Аль-Камар", translation: "Луна" },
  { name: "Ар-Рахман", translation: "Милостивый" },
  { name: "Аль-Вакыа", translation: "Событие" },
  { name: "Аль-Хадид", translation: "Железо" },
  { name: "Аль-Муджадила", translation: "Препирающаяся" },
  { name: "Аль-Хашр", translation: "Сбор" },
  { name: "Аль-Мумтахана", translation: "Испытуемая" },
  { name: "Ас-Сафф", translation: "Ряды" },
  { name: "Аль-Джумуа", translation: "Собрание" },
  { name: "Аль-Мунафикун", translation: "Лицемеры" },
  { name: "Ат-Тагабун", translation: "Взаимное обделение" },
  { name: "Ат-Талак", translation: "Развод" },
  { name: "Ат-Тахрим", translation: "Запрещение" },
  { name: "Аль-Мульк", translation: "Власть" },
  { name: "Аль-Калям", translation: "Перо" },
  { name: "Аль-Хакка", translation: "Неминуемое" },
  { name: "Аль-Мааридж", translation: "Ступени" },
  { name: "Нух", translation: "Нух" },
  { name: "Аль-Джинн", translation: "Джинны" },
  { name: "Аль-Муззаммиль", translation: "Закутавшийся" },
  { name: "Аль-Муддассир", translation: "Завернувшийся" },
  { name: "Аль-Кияма", translation: "Воскресение" },
  { name: "Аль-Инсан", translation: "Человек" },
  { name: "Аль-Мурсалят", translation: "Посылаемые" },
  { name: "Ан-Наба", translation: "Весть" },
  { name: "Ан-Назиат", translation: "Вырывающие" },
  { name: "Абаса", translation: "Нахмурился" },
  { name: "Ат-Таквир", translation: "Скручивание" },
  { name: "Аль-Инфитар", translation: "Раскалывание" },
  { name: "Аль-Мутаффифин", translation: "Обвешивающие" },
  { name: "Аль-Иншикак", translation: "Разверзание" },
  { name: "Аль-Бурудж", translation: "Созвездия" },
  { name: "Ат-Тарик", translation: "Ночной путник" },
  { name: "Аль-Аля", translation: "Высочайший" },
  { name: "Аль-Гашия", translation: "Покрывающее" },
  { name: "Аль-Фаджр", translation: "Заря" },
  { name: "Аль-Баляд", translation: "Город" },
  { name: "Аш-Шамс", translation: "Солнце" },
  { name: "Аль-Лейль", translation: "Ночь" },
  { name: "Ад-Духа", translation: "Утро" },
  { name: "Аш-Шарх", translation: "Раскрытие" },
  { name: "Ат-Тин", translation: "Смоковница" },
  { name: "Аль-Аляк", translation: "Сгусток крови" },
  { name: "Аль-Кадр", translation: "Предопределение" },
  { name: "Аль-Баййина", translation: "Ясное знамение" },
  { name: "Аз-Зальзаля", translation: "Сотрясение" },
  { name: "Аль-Адият", translation: "Скачущие" },
  { name: "Аль-Кариа", translation: "Великое бедствие" },
  { name: "Ат-Такасур", translation: "Страсть к приумножению" },
  { name: "Аль-Аср", translation: "Время" },
  { name: "Аль-Хумаза", translation: "Хулитель" },
  { name: "Аль-Филь", translation: "Слон" },
  { name: "Курайш", translation: "Курейшиты" },
  { name: "Аль-Маун", translation: "Мелочная помощь" },
  { name: "Аль-Каусар", translation: "Изобилие" },
  { name: "Аль-Кафирун", translation: "Неверующие" },
  { name: "Ан-Наср", translation: "Помощь" },
  { name: "Аль-Масад", translation: "Пальмовые волокна" },
  { name: "Аль-Ихлас", translation: "Очищение веры" },
  { name: "Аль-Фаляк", translation: "Рассвет" },
  { name: "Ан-Нас", translation: "Люди" }
]

export function getSurahRuMeta(number: number): SurahRuMeta | null {
  return data[number - 1] ?? null
}